---
sidebar: sidebar 
permalink: task_planning_your_config.html 
keywords: license, disk, ebs, storage, size, write speed, volume usage, explore, standard, premium, byol, ec2, capacity, limit, configurations, virtual machine, vm, regions, supported disks, disk types, general purpose, gp2 provisioned IOPS, piops, throughput optimized, cold, SSD, HDD, st1, sc1, premium storage, standard storage, use profile, thin provisioning, deduplication, compression, Cloud Volumes ONTAP explore, Cloud Volumes ONTAP standard, Cloud Volumes ONTAP premium, Cloud Volumes ONTAP byol, shared instance, dedicated instance, write speed, high write speed, normal write speed, network information, worksheet, limit, limits, storage limits, volume limit, aggregate limit, maximum volume size, maximum aggregate size 
summary: Quando si implementa Cloud Volumes ONTAP, è possibile scegliere un sistema preconfigurato che soddisfi i requisiti del carico di lavoro oppure creare una configurazione personalizzata. Se si sceglie una configurazione personalizzata, è necessario comprendere le opzioni disponibili. 
---
= Pianificazione della configurazione di Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Quando si implementa Cloud Volumes ONTAP, è possibile scegliere un sistema preconfigurato che soddisfi i requisiti del carico di lavoro oppure creare una configurazione personalizzata. Se si sceglie una configurazione personalizzata, è necessario comprendere le opzioni disponibili.



== Scelta di un tipo di licenza

Cloud Volumes ONTAP è disponibile in due opzioni di prezzo: Pay-as-you-go e Bring Your Own License (BYOL). Per il pay-as-you-go, puoi scegliere tra tre licenze: Explore, Standard o Premium. Ogni licenza offre diverse capacità e opzioni di calcolo.

* https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_configs_aws_97.html["Configurazioni supportate per Cloud Volumes ONTAP 9.7 in AWS"^]
* https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_configs_azure_97.html["Configurazioni supportate per Cloud Volumes ONTAP 9.7 in Azure"^]
* https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_configs_gcp_97.html["Configurazioni supportate per Cloud Volumes ONTAP 9.7 in GCP"^]




== Comprendere i limiti dello storage

Il limite di capacità raw per un sistema Cloud Volumes ONTAP è legato alla licenza. Ulteriori limiti influiscono sulle dimensioni degli aggregati e dei volumi. Durante la pianificazione della configurazione, è necessario conoscere questi limiti.

* https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_limits_aws_97.html["Limiti di storage per Cloud Volumes ONTAP 9.7 in AWS"]
* https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_limits_azure_97.html["Limiti di storage per Cloud Volumes ONTAP 9.7 in Azure"]
* https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_limits_gcp_97.html["Limiti di storage per Cloud Volumes ONTAP 9.7 in GCP"]




== Scelta della velocità di scrittura

Cloud Manager consente di scegliere un'impostazione della velocità di scrittura per i sistemi Cloud Volumes ONTAP a nodo singolo. Prima di scegliere una velocità di scrittura, è necessario comprendere le differenze tra le impostazioni normali e alte e i rischi e le raccomandazioni quando si utilizza un'elevata velocità di scrittura.



==== Differenza tra la velocità di scrittura normale e l'alta velocità di scrittura

Quando si sceglie la normale velocità di scrittura, i dati vengono scritti direttamente su disco, riducendo così la probabilità di perdita di dati in caso di un'interruzione non pianificata del sistema.

Quando si sceglie un'elevata velocità di scrittura, i dati vengono memorizzati nel buffer prima che vengano scritti su disco, garantendo prestazioni di scrittura più rapide. A causa di questo caching, vi è la possibilità di perdita di dati in caso di un'interruzione non pianificata del sistema.

La quantità di dati che è possibile perdere in caso di interruzione non pianificata del sistema è l'intervallo degli ultimi due punti di coerenza. Un punto di coerenza è l'azione di scrittura dei dati bufferizzati su disco. Un punto di coerenza si verifica quando il registro di scrittura è pieno o dopo 10 secondi (a seconda di quale condizione si verifica per prima). Tuttavia, le performance del volume di AWS EBS possono influire sul tempo di elaborazione dei punti di coerenza.



==== Quando utilizzare un'elevata velocità di scrittura

L'elevata velocità di scrittura è una buona scelta se per il carico di lavoro sono richieste prestazioni di scrittura rapide e se si può resistere al rischio di perdita di dati in caso di un'interruzione non pianificata del sistema.



==== Consigli quando si utilizza un'elevata velocità di scrittura

Se si attiva l'alta velocità di scrittura, è necessario garantire la protezione in scrittura a livello di applicazione.



== Scelta di un profilo di utilizzo del volume

ONTAP include diverse funzionalità di efficienza dello storage che consentono di ridurre la quantità totale di storage necessaria. Quando crei un volume in Cloud Manager, puoi scegliere un profilo che abiliti queste funzionalità o un profilo che le disabiliti. Dovresti saperne di più su queste funzionalità per aiutarti a decidere quale profilo utilizzare.

Le funzionalità di efficienza dello storage NetApp offrono i seguenti vantaggi:

Thin provisioning:: Presenta uno storage logico maggiore per gli host o gli utenti rispetto al pool di storage fisico. Invece di preallocare lo spazio di storage, lo spazio di storage viene allocato dinamicamente a ciascun volume durante la scrittura dei dati.
Deduplica:: Migliora l'efficienza individuando blocchi di dati identici e sostituendoli con riferimenti a un singolo blocco condiviso. Questa tecnica riduce i requisiti di capacità dello storage eliminando blocchi di dati ridondanti che risiedono nello stesso volume.
Compressione:: Riduce la capacità fisica richiesta per memorizzare i dati comprimendo i dati all'interno di un volume su storage primario, secondario e di archivio.




== Pianificazione AWS

Pianificare l'implementazione di Cloud Volumes ONTAP in AWS dimensionando il sistema ed esaminando le informazioni di rete da inserire.

* <<Dimensionamento del sistema in AWS>>
* <<Foglio di lavoro delle informazioni di rete AWS>>




=== Dimensionamento del sistema in AWS

Il dimensionamento del sistema Cloud Volumes ONTAP può aiutarti a soddisfare i requisiti di performance e capacità. Quando si sceglie un tipo di istanza, un tipo di disco e una dimensione del disco, è necessario tenere presenti alcuni punti chiave:

Tipo di istanza::
+
--
* Abbina i requisiti di carico di lavoro al throughput massimo e agli IOPS per ogni tipo di istanza EC2.
* Se diversi utenti scrivono nel sistema contemporaneamente, scegliere un tipo di istanza con CPU sufficienti per gestire le richieste.
* Se si dispone di un'applicazione in gran parte in lettura, scegliere un sistema con una quantità di RAM sufficiente.
+
** https://aws.amazon.com/ec2/instance-types/["Documentazione AWS: Tipi di istanze Amazon EC2"^]
** https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSOptimized.html["Documentazione AWS: Istanze ottimizzate per Amazon EBS"^]




--
Tipo di disco EBS:: Gli SSD General Purpose sono il tipo di disco più comune per Cloud Volumes ONTAP. Per visualizzare i casi di utilizzo dei dischi EBS, fare riferimento a. http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html["Documentazione AWS: Tipi di volume EBS"^].
Dimensione del disco EBS:: Quando si avvia un sistema Cloud Volumes ONTAP, è necessario scegliere una dimensione iniziale del disco. Dopo di che, è possibile link:concept_storage_management.html["Lascia che Cloud Manager gestisca la capacità di un sistema per te"], ma se lo si desidera link:task_provisioning_storage.html#creating-aggregates["costruisci gli aggregati"], tenere presente quanto segue:
+
--
* Tutti i dischi di un aggregato devono avere le stesse dimensioni.
* Le prestazioni dei dischi EBS sono legate alle dimensioni dei dischi. La dimensione determina gli IOPS di riferimento e la durata massima del burst per i dischi SSD e il throughput di base e burst per i dischi HDD.
* In definitiva, è necessario scegliere le dimensioni del disco che offrono le _prestazioni sostenute_ necessarie.
* Anche se si scelgono dischi più grandi (ad esempio, sei dischi da 4 TB), è possibile che non si ottengano tutti gli IOPS perché l'istanza EC2 può raggiungere il limite di larghezza di banda.
+
Per ulteriori informazioni sulle prestazioni dei dischi EBS, fare riferimento a. http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html["Documentazione AWS: Tipi di volume EBS"^].



--


Guarda il seguente video per ulteriori dettagli sul dimensionamento del tuo sistema Cloud Volumes ONTAP in AWS:

video::GELcXmOuYPw[youtube,width=848,height=480]


=== Foglio di lavoro delle informazioni di rete AWS

Quando si avvia Cloud Volumes ONTAP in AWS, è necessario specificare i dettagli della rete VPC. È possibile utilizzare un foglio di lavoro per raccogliere le informazioni dall'amministratore.



==== Informazioni di rete per Cloud Volumes ONTAP

[cols="30,70"]
|===
| Informazioni AWS | Il tuo valore 


| Regione |  


| VPC |  


| Subnet |  


| Gruppo di sicurezza (se si utilizza il proprio) |  
|===


==== Informazioni di rete per una coppia ha in più AZS

[cols="30,70"]
|===
| Informazioni AWS | Il tuo valore 


| Regione |  


| VPC |  


| Gruppo di sicurezza (se si utilizza il proprio) |  


| Zona di disponibilità del nodo 1 |  


| Subnet del nodo 1 |  


| Zona di disponibilità del nodo 2 |  


| Subnet del nodo 2 |  


| Area di disponibilità del mediatore |  


| Subnet del mediatore |  


| Coppia di chiavi per il mediatore |  


| Indirizzo IP mobile per la porta di gestione del cluster |  


| Indirizzo IP mobile per i dati sul nodo 1 |  


| Indirizzo IP mobile per i dati sul nodo 2 |  


| Tabelle di routing per gli indirizzi IP mobili |  
|===


== Pianificazione di Azure

Pianifica la tua implementazione di Cloud Volumes ONTAP in Azure dimensionando il tuo sistema ed esaminando le informazioni di rete che devi inserire.

* <<Dimensionamento del sistema in Azure>>
* <<Foglio di lavoro con le informazioni di rete di Azure>>




=== Dimensionamento del sistema in Azure

Il dimensionamento del sistema Cloud Volumes ONTAP può aiutarti a soddisfare i requisiti di performance e capacità. Quando si sceglie un tipo di macchina virtuale, un tipo di disco e una dimensione del disco, è necessario tenere presenti alcuni punti chiave:

Tipo di macchina virtuale:: Esaminare i tipi di macchine virtuali supportati in http://docs.netapp.com/cloud-volumes-ontap/us-en/index.html["Note di rilascio di Cloud Volumes ONTAP"^] Quindi, esaminare i dettagli relativi a ciascun tipo di macchina virtuale supportato. Tenere presente che ogni tipo di macchina virtuale supporta un numero specifico di dischi dati.
+
--
* https://docs.microsoft.com/en-us/azure/virtual-machines/linux/sizes-general#dsv2-series["Documentazione di Azure: Dimensioni generali delle macchine virtuali"^]
* https://docs.microsoft.com/en-us/azure/virtual-machines/linux/sizes-memory#dsv2-series-11-15["Documentazione di Azure: Dimensioni delle macchine virtuali ottimizzate per la memoria"^]


--
Tipo di disco Azure:: Quando crei volumi per Cloud Volumes ONTAP, devi scegliere lo storage cloud sottostante che Cloud Volumes ONTAP utilizza come disco.
+
--
I sistemi HA utilizzano i blob di pagina Premium. Nel frattempo, i sistemi a nodo singolo possono utilizzare due tipi di dischi gestiti Azure:

* _Dischi gestiti SSD Premium_ offrono performance elevate per carichi di lavoro i/o-intensive a un costo più elevato.
* I _dischi gestiti SSD standard_ offrono performance costanti per i carichi di lavoro che richiedono IOPS ridotti.
* _Dischi gestiti HDD standard_ sono una buona scelta se non hai bisogno di IOPS elevati e vuoi ridurre i costi.
+
Per ulteriori informazioni sui casi di utilizzo di questi dischi, vedere https://azure.microsoft.com/documentation/articles/storage-introduction/["Documentazione di Microsoft Azure: Introduzione allo storage Microsoft Azure"^].



--
Dimensioni del disco Azure:: Quando si avviano le istanze di Cloud Volumes ONTAP, è necessario scegliere la dimensione predefinita del disco per gli aggregati. Cloud Manager utilizza questa dimensione del disco per l'aggregato iniziale e per qualsiasi aggregato aggiuntivo creato quando si utilizza l'opzione di provisioning semplice. È possibile creare aggregati che utilizzano una dimensione del disco diversa da quella predefinita di link:task_provisioning_storage.html#creating-aggregates["utilizzando l'opzione di allocazione avanzata"].
+
--

TIP: Tutti i dischi di un aggregato devono avere le stesse dimensioni.

Quando si sceglie una dimensione del disco, è necessario prendere in considerazione diversi fattori. Le dimensioni del disco influiscono sul costo dello storage, sulle dimensioni dei volumi che è possibile creare in un aggregato, sulla capacità totale disponibile per Cloud Volumes ONTAP e sulle performance dello storage.

Le prestazioni di Azure Premium Storage sono legate alle dimensioni del disco. I dischi più grandi offrono IOPS e throughput più elevati. Ad esempio, la scelta di dischi da 1 TB può offrire prestazioni migliori rispetto ai dischi da 500 GB, a un costo superiore.

Non esistono differenze di performance tra le dimensioni dei dischi per lo storage standard. È necessario scegliere le dimensioni del disco in base alla capacità richiesta.

Fare riferimento a Azure per IOPS e throughput in base alle dimensioni del disco:

* https://azure.microsoft.com/en-us/pricing/details/managed-disks/["Microsoft Azure: Prezzi dei dischi gestiti"^]
* https://azure.microsoft.com/en-us/pricing/details/storage/page-blobs/["Microsoft Azure: Page Blobs pricing"^]


--




=== Foglio di lavoro con le informazioni di rete di Azure

Quando si implementa Cloud Volumes ONTAP in Azure, è necessario specificare i dettagli della rete virtuale. È possibile utilizzare un foglio di lavoro per raccogliere le informazioni dall'amministratore.

[cols="30,70"]
|===
| Informazioni su Azure | Il tuo valore 


| Regione |  


| Rete virtuale (VNET) |  


| Subnet |  


| Gruppo di sicurezza di rete (se si utilizza il proprio) |  
|===


== Pianificazione GCP

Pianifica la tua implementazione di Cloud Volumes ONTAP nella piattaforma cloud di Google dimensionando il tuo sistema ed esaminando le informazioni di rete che devi inserire.

* <<Dimensionamento del sistema in GCP>>
* <<Foglio di lavoro delle informazioni di rete GCP>>




=== Dimensionamento del sistema in GCP

Il dimensionamento del sistema Cloud Volumes ONTAP può aiutarti a soddisfare i requisiti di performance e capacità. Quando si sceglie un tipo di macchina, un tipo di disco e una dimensione del disco, occorre tenere presente alcuni punti chiave:

Tipo di macchina:: Esaminare i tipi di computer supportati in http://docs.netapp.com/cloud-volumes-ontap/us-en/index.html["Note di rilascio di Cloud Volumes ONTAP"^] Quindi, esamina i dettagli di Google relativi a ciascun tipo di computer supportato. Abbina i requisiti di carico di lavoro al numero di vCPU e di memoria per il tipo di computer. Si noti che ogni core della CPU aumenta le performance di rete.
+
--
Per ulteriori informazioni, fare riferimento a quanto segue:

* https://cloud.google.com/compute/docs/machine-types#n1_machine_types["Documentazione di Google Cloud: Tipi di computer standard N1"^]
* https://cloud.google.com/docs/compare/data-centers/networking#performance["Documentazione Google Cloud: Performance"^]


--
Tipo di disco GCP:: Quando crei volumi per Cloud Volumes ONTAP, devi scegliere lo storage cloud sottostante utilizzato da Cloud Volumes ONTAP per un disco. Il tipo di disco può essere _dischi persistenti SSD Zonal_ o _dischi persistenti standard Zonal_.
+
--
I dischi persistenti SSD sono ideali per i carichi di lavoro che richiedono elevati tassi di IOPS casuali, mentre i dischi persistenti standard sono economici e possono gestire operazioni di lettura/scrittura sequenziali. Per ulteriori informazioni, vedere https://cloud.google.com/compute/docs/disks/#pdspecs["Documentazione di Google Cloud: Dischi persistenti zonali (Standard e SSD)"^].

--
Dimensione del disco GCP:: Quando si implementa un sistema Cloud Volumes ONTAP, è necessario scegliere una dimensione iniziale del disco. In seguito, puoi lasciare che Cloud Manager gestisca la capacità di un sistema per te, ma se vuoi creare aggregati, tieni presente quanto segue:
+
--
* Tutti i dischi di un aggregato devono avere le stesse dimensioni.
* Determinare lo spazio necessario, tenendo in considerazione le performance.
* Le performance dei dischi persistenti si ridimensionano automaticamente in base alle dimensioni del disco e al numero di vCPU disponibili per il sistema.
+
Per ulteriori informazioni, fare riferimento a quanto segue:

+
** https://cloud.google.com/compute/docs/disks/#pdspecs["Documentazione di Google Cloud: Dischi persistenti zonali (Standard e SSD)"^]
** https://cloud.google.com/compute/docs/disks/performance["Documentazione di Google Cloud: Ottimizzazione delle performance di dischi persistenti e SSD locali"^]




--




=== Foglio di lavoro delle informazioni di rete GCP

Quando si implementa Cloud Volumes ONTAP in GCP, è necessario specificare i dettagli della rete virtuale. È possibile utilizzare un foglio di lavoro per raccogliere le informazioni dall'amministratore.

[cols="30,70"]
|===
| Informazioni GCP | Il tuo valore 


| Regione |  


| Zona |  


| Rete VPC |  


| Subnet |  


| Policy firewall (se si utilizza il proprio) |  
|===